--DROP TABLE FUNCTIONALMODELDATAFIELD IF EXISTS  ;
--DROP TABLE FUNCTIONALMODEL IF EXISTS  ;
--DROP TABLE DATAFIELD IF EXISTS  ;
--DROP TABLE DATAGROUP IF EXISTS  ;
--DROP TABLE FUNCTIONALPROCESS IF EXISTS  ;
--DROP TABLE FUNCTIONALSUBPROCESS IF EXISTS  ;
--
--DROP TABLE SYSTEMCONTEXT IF EXISTS  ;
--DROP TABLE DataMovement IF EXISTS  ;

--
CREATE TABLE IF NOT EXISTS SystemContext  (
	id BIGINT IDENTITY NOT NULL PRIMARY KEY ,
	SystemContextId BIGINT ,
	version BIGINT DEFAULT 0,
	name VARCHAR(100) NOT NULL,
	notes VARCHAR(200) ,
	diagram BLOB ,
	userid VARCHAR(100) NOT NULL ,
	createdtime TIMESTAMP DEFAULT NOW()
)   ;

CREATE TABLE IF NOT EXISTS DataGroup  (
	id BIGINT IDENTITY NOT NULL PRIMARY KEY ,
	DATAGROUPID BIGINT,
	SYSTEMCONTEXTID BIGINT,
	VERSION BIGINT DEFAULT 0,
	NAME VARCHAR(100) NOT NULL,
	NOTES VARCHAR(200) ,
	USERID VARCHAR(100) NOT NULL ,
	CREATETIME TIMESTAMP DEFAULT NOW()
)   ;
--
CREATE TABLE IF NOT EXISTS  DATAFIELD  (
	id BIGINT IDENTITY NOT NULL PRIMARY KEY ,
	DATAFIELDID BIGINT  ,
	DATAGROUPID BIGINT  ,
	VERSION BIGINT DEFAULT 0,
	NAME VARCHAR(100) NOT NULL,
	USERID VARCHAR(100) NOT NULL ,
	CREATETIME TIMESTAMP DEFAULT NOW()
)   ;

CREATE TABLE IF NOT EXISTS FUNCTIONALPROCESS  (
	id BIGINT IDENTITY NOT NULL PRIMARY KEY ,
	FUNCTIONALPROCESSID BIGINT  ,
	SYSTEMCONTEXTID BIGINT  ,
	VERSION BIGINT default 0,
	NAME VARCHAR(100) NOT NULL,
	NOTES VARCHAR(200) ,
	USERID VARCHAR(100) NOT NULL ,
	CREATETIME TIMESTAMP DEFAULT NOW()
)   ;
--
CREATE TABLE IF NOT EXISTS FUNCTIONALSUBPROCESS  (
    id BIGINT IDENTITY NOT NULL PRIMARY KEY ,
	FUNCTIONALSUBPROCESSID BIGINT ,
	FUNCTIONALPROCESSID BIGINT  ,
	VERSION BIGINT default 0,
	NAME VARCHAR(100) NOT NULL ,
	USERID VARCHAR(100) NOT NULL ,
	CREATETIME TIMESTAMP DEFAULT NOW()
)   ;
--

CREATE TABLE IF NOT EXISTS DataMovement  (
	id BIGINT IDENTITY NOT NULL PRIMARY KEY ,
	SizingContextId BIGINT  ,
	SubProcessId BIGINT  ,
	DataGroupId BIGINT  ,
	DataFieldId BIGINT  ,
  	Type VARCHAR(100),
	version BIGINT default 0,
	CreatedBy VARCHAR(100) NOT NULL ,
	CreatedTime TIMESTAMP DEFAULT NOW()
)   ;


-- these are all commented out because

select * from dual;

--DROP sequence seq_SystemContext if exists;
CREATE SEQUENCE IF NOT EXISTS seq_SystemContext;

--DROP sequence seq_DataGroup if exists;
CREATE SEQUENCE IF NOT EXISTS seq_DataGroup;

--DROP sequence seq_DataGroup if exists;
CREATE SEQUENCE IF NOT EXISTS seq_DataField;

--DROP sequence seq_FunctionalProcess if exists;
CREATE SEQUENCE IF NOT EXISTS seq_FunctionalProcess;







