
CREATE TABLE IF NOT EXISTS DataGroup  (
	id BIGINT IDENTITY NOT NULL PRIMARY KEY ,
	DATAGROUPID BIGINT,
	SYSTEMCONTEXTID BIGINT,
	VERSION BIGINT DEFAULT 0,
	NAME VARCHAR(100) NOT NULL,
	NOTES VARCHAR(200) ,
	USERID VARCHAR(100) NOT NULL ,
	CREATETIME TIMESTAMP DEFAULT NOW()
)   ;



--DROP sequence seq_DataGroup if exists;
CREATE SEQUENCE IF NOT EXISTS seq_DataGroup;
