--
CREATE TABLE IF NOT EXISTS  DATAFIELD  (
	id BIGINT IDENTITY NOT NULL PRIMARY KEY ,
	DATAFIELDID BIGINT  ,
	DATAGROUPID BIGINT  ,
	VERSION BIGINT DEFAULT 0,
	NAME VARCHAR(100) NOT NULL,
	createdby VARCHAR(100) NOT NULL ,
	createdtime TIMESTAMP DEFAULT NOW()
)   ;


--DROP sequence seq_DataGroup if exists;
CREATE SEQUENCE IF NOT EXISTS seq_DataField;
