CREATE TABLE IF NOT EXISTS FUNCTIONALSUBPROCESS  (
    id BIGINT IDENTITY NOT NULL PRIMARY KEY ,
	FUNCTIONALSUBPROCESSID BIGINT ,
	FUNCTIONALPROCESSID BIGINT  ,
	VERSION BIGINT default 0,
	NAME VARCHAR(100) NOT NULL ,
	createdby VARCHAR(100) NOT NULL ,
	createdtime TIMESTAMP DEFAULT NOW()
)   ;
--